- name: Install arm, armv7 and aarch64 Linkers
  if: runner.os == 'Linux'
  run: |
    sudo apt install gcc-arm-linux-gnueabihf
    sudo apt install gcc-aarch64-linux-gnu
    sudo apt-get install -y libwayland-dev

