[package]
name = "pigg"
version = "0.1.0"
edition = "2021"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
# Add other names above if they want ^^^^
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
#homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"

[[bin]]
name = "piggui"
path = "src/piggui.rs"
required-features = ["gui"]

[[bin]]
name = "piglet"
path = "src/piglet.rs"
required-features = ["pi"]

[features]
default = []
pi = ["rppal"]
pico = [] #embassy
gui = ["iced", "tokio", "serde"]

[dependencies]
# for interacting with GPIO on the Raspberry Pi
rppal = { version = "0.17.1", optional = true }

# for GUI
iced = { version = "0.12.1", features = ["tokio", "debug", "canvas", "advanced"], optional = true }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal",] , optional = true }
iced_native = { version = "0.10.3", optional = true }
tokio = { version = "1", features = ["sync"], optional = true }
serde = { version = "1.0.202", features = ["derive"], optional = true }
serde_json = "1.0.117"

[dev-dependencies]
tempfile = "3"