[package]
name = "pigg"
version = "0.3.0"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"

[[bin]]
name = "piggui"
path = "src/piggui.rs"

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = []
discovery = []

[dependencies]
# use in piggui and piglet
chrono = { version = "0.4", default-features = false, features = ["now", "serde"] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.122", default-features = false, features = ["std"] }
serde_arrays = "0.1.0"
clap = { version = "4.5.11", default-features = false, features = ["std"] }
rand = { version = "0.8.5" }
iroh-net = { version = "0.19.0" }
anyhow = { version = "1" }
futures-lite = { version = "2.3" }
tokio = { version = "1.39.2", default-features = false, features = ["time", "rt"] }

# for interacting with GPIO on the Raspberry Pi
rppal = { version = "0.18.0", optional = true }

# used in piglet only
log = "0.4.22"
env_logger = "0.11.5"
service-manager = "0.7.1"
sysinfo = "0.31.1"

# used by piggui in GUI only
iced = { version = "0.12.1", default-features = false, features = ["tokio", "debug", "canvas", "advanced"] }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal", "menu"] }
iced_futures = { version = "0.12.0", default-features = false }
iced_native = { version = "0.10.3", default-features = false }
plotters-iced = { version = "0.10", default-features = false }
plotters = { version = "0.3", default_features = false, features = [
    "chrono",
    "line_series",
] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
once_cell = "1.19.0"
lyon_algorithms = "1.0"

[dev-dependencies]
tempfile = "3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.14.1"

[target.aarch64-unknown-linux-gnu.dependencies]
rppal = "0.18.0"

[target.armv7-unknown-linux-gnueabihf.dependencies]
rppal = "0.18.0"
