[package]
name = "pigg"
version = "0.3.2"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"
exclude = [".github", "assets/", "codecov.yml", "configs/", "Makefile", ".cargo_vcs_info_.json"]

[[bin]]
name = "piggui"
path = "src/piggui.rs"

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = []
discovery = []

[dependencies]
derive_more = "=1.0.0-beta.6" # To fix iroh-net issue

# use in piggui and piglet
chrono = { version = "0.4", default-features = false, features = ["now", "serde"] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.122", default-features = false, features = ["std"] }
serde_arrays = { version = "0.1.0", default-features = false }
clap = { version = "4.5.11", default-features = false, features = ["std"] }
rand = { version = "0.8.5", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt", "env-filter"] }
iroh-net = { version = "0.19.0", default-features = false }
anyhow = { version = "1", default-features = false }
futures-lite = { version = "2.3", default-features = false }
tokio = { version = "1.39.2", default-features = false, features = ["time", "rt"] }

# used in piglet only
log = { version = "0.4.22", default-features = false }
env_logger = { version = "0.11.5", default-features = false }
service-manager = { version = "0.7.1", default-features = false }
sysinfo = { version = "0.31.2", default-features = false, features = ["system"] }

# used by piggui in GUI only
iced = { version = "0.12.1", default-features = false, features = ["tokio", "debug", "canvas", "advanced"] }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal", "menu"] }
iced_futures = { version = "0.12.0", default-features = false }
iced_native = { version = "0.10.3", default-features = false }
plotters-iced = { version = "0.10", default-features = false }
plotters = { version = "0.3", default_features = false, features = [
    "chrono",
    "line_series",
] }
tracing = { version = "0.1.40", default-features = false }
once_cell = { version = "1.19.0", default-features = false }
lyon_algorithms = { version = "1.0", default-features = false }

[dev-dependencies]
tempfile = "3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.14.1"

[target.aarch64-unknown-linux-gnu.dependencies]
rppal = "0.18.0"

[target.armv7-unknown-linux-gnueabihf.dependencies]
rppal = "0.18.0"
