[package]
name = "pigg"
version = "0.2.0"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"

[[bin]]
name = "piggui"
path = "src/piggui.rs"
required-features = ["gui"]

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = []
pi_hw = ["rppal"]
fake_hw = ["rand"]
gui = ["iced", "iced_futures", "rfd", "plotters-iced", "plotters"]

[dependencies]
# use in piggui and piglet
chrono = { version = "0.4", default-features = false, features = ["now", "serde"] }
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.120", default-features = false, features = ["std"] }
serde_arrays = "0.1.0"
clap = { version = "4.5.8", default-features = false, features = ["std"] }
rand = { version = "0.8.5", optional = true }
iroh-net = { version = "0.19.0" }
anyhow = { version = "1" }
futures-lite = { version = "2.3" }
tokio = { version = "1", default-features = false, features = ["time", "rt"] }

# for interacting with GPIO on the Raspberry Pi
rppal = { version = "0.18.0", optional = true }

# used in piglet only
log = "0.4.22"
env_logger = "0.11.3"

# used by piggui in GUI only
iced = { version = "0.12.1", default-features = false, features = ["tokio", "debug", "canvas", "advanced"], optional = true }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal", ], optional = true }
iced_futures = { version = "0.12.0", default-features = false, optional = true }
iced_native = { version = "0.10.3", default-features = false, optional = true }
rfd = { version = "0.14.1", optional = true }
plotters-iced = { version = "0.10", default-features = false, optional = true }
plotters = { version = "0.3", optional = true, default_features = false, features = [
    "chrono",
    "line_series",
] }

[dev-dependencies]
tempfile = "3"