[package]
name = "pigg"
version = "0.1.0"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"

[[bin]]
name = "piggui"
path = "src/piggui.rs"
required-features = ["gui"]

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = ["gui"]
pi = ["rppal"]
pico = [] #embassy
gui = ["iced", "tokio", "serde", "serde_json", "iced_futures", "rfd", "plotters-iced", "plotters", "chrono",
    "sysinfo"]

[dependencies]
# for interacting with GPIO on the Raspberry Pi
rppal = { version = "0.18.0", optional = true }

# for GUI
iced = { version = "0.12.1", default-features = false, features = ["tokio", "debug", "canvas", "advanced"], optional = true }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal", ], optional = true }
iced_futures = { version = "0.12.0", default-features = false, optional = true }
iced_native = { version = "0.10.3", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
serde = { version = "1.0.203", features = ["derive"], optional = true }
serde_json = { version = "1.0.117", optional = true }
rfd = { version = "0.14.1", optional = true }
plotters-iced = { version = "0.10", optional = true }
plotters = { version = "0.3", optional = true, default_features = false, features = [
    "chrono",
    "line_series",
] }
chrono = { version = "0.4", default-features = false, optional = true }
sysinfo = { version = "0.30", default_features = false, optional = true }

[dev-dependencies]
tempfile = "3"