[package]
name = "pigg"
version = "0.3.4"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"
exclude = [".github", "assets/", "codecov.yml", "configs/", "Makefile", ".cargo_vcs_info.json",
    ".gitignore", "tests"]

[package.metadata.wix]
upgrade-guid = "7DCB054F-6CE0-4914-876E-AEA0C2E91328"
path-guid = "17155407-8DA8-45BD-8C67-91FE4C7E99AA"

[[bin]]
name = "piggui"
path = "src/piggui.rs"

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = []

[dependencies]
# use in piggui and piglet
chrono = { version = "0.4", default-features = false, features = ["now", "serde"] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.122", default-features = false, features = ["std"] }
serde_arrays = { version = "0.1.0", default-features = false }
rand = { version = "0.8.5", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt", "env-filter"] }
iroh-net = { version = "0.22.0", default-features = false, features = ["local_swarm_discovery"] }
anyhow = { version = "1", default-features = false }
futures-lite = { version = "2.3", default-features = false }
tokio = { version = "1.39.2", default-features = false, features = ["time", "rt"] }

# used in piglet only
log = { version = "0.4.22", default-features = false }
service-manager = { version = "0.7.1", default-features = false }
sysinfo = { version = "0.31.2", default-features = false, features = ["system"] }

# used by piggui in GUI only
iced = { version = "0.13.0-dev", git = "https://github.com/iced-rs/iced.git", default-features = false, features = ["tokio"] }
iced_aw = { version = "0.9.3", get = "https://github.com/iced-rs/iced_aw.git", default-features = false, features = ["menu"] }
iced_futures = { version = "0.12.0", default-features = false }
plotters-iced = { version = "0.10", default-features = false }
plotters = { version = "0.3", default_features = false, features = [
    "chrono",
    "line_series",
] }
tracing = { version = "0.1.40", default-features = false }
once_cell = { version = "1.19.0", default-features = false }
lyon_algorithms = { version = "1.0", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tempfile = "3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.14.1"
clap = { version = "4.5.11", default-features = false, features = ["std"] }

[target.aarch64-unknown-linux-gnu.dependencies]
rppal = "0.18.0"

[target.armv7-unknown-linux-gnueabihf.dependencies]
rppal = "0.18.0"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.3.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# A GitHub repo to push Homebrew formulas to
tap = "andrewdavidmackenzie/pigg-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"
