[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# A GitHub repo to push Homebrew formulas to
tap = "andrewdavidmackenzie/pigg-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-pc-windows-msvc", "armv7-unknown-linux-gnueabihf", "armv7-unknown-linux-musleabihf", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc", "arm-unknown-linux-gnueabihf", "arm-unknown-linux-musleabihf"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
github-build-setup = "../install-arm-linkers.yml"
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["70.pigg.rules"]

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"
x86_64-apple-darwin = "macos-13"
x86_64-unknown-linux-gnu = "ubuntu-24.04"
x86_64-pc-windows-msvc = "windows-latest"
armv7-unknown-linux-musleabihf = "ubuntu-24.04"

[[dist.extra-artifacts]]
artifacts = [
    "porky/target/thumbv6m-none-eabi/release/porky_pico_w.uf2",
    "porky/target/thumbv6m-none-eabi/release/porky_pico_w2.uf2",
    "porky/target/thumbv6m-none-eabi/release/porky_pico.uf2",
    "porky/target/thumbv6m-none-eabi/release/porky_pico2.uf2",
    "70.pigg.rules"
]
# For porky binary builds - install the 'elf2uf2-rs' tool, then build the uf2 files for artifacts above
build = ["make", "-C", "porky", "install-uf2", "uf2s"]
