[package]
name = "pignet"
version = "0.6.0"
edition = "2021"

[features]
default = ["iroh", "tcp", "usb", "discovery"]
tcp = ["portpicker", "local-ip-address"]
discovery = ["iroh/discovery-local-network", "mdns-sd"]
no_std = []
usb = ["nusb"]

[dependencies]
pigdef = { version = "0.6", path = "../pigdef" }
pigpio = { version = "0.6", path = "../pigpio" }

iroh = { version = "0.32", default-features = false, optional = true }
portpicker = { version = "0.1.1", default-features = false, optional = true }
nusb = { version = "0.1.12", default-features = false, optional = true }
mdns-sd = { version = "0.13.2", default-features = false, optional = true }
local-ip-address = { version = "0.6.3", default-features = false, optional = true }
postcard = { version = "1.1.1", features = ["alloc"] }
anyhow = "1.0.95"
log = "0.4.25"
async-std = "1.13.0"
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
tokio = "1.43.0"
