[package]
name = "porky"
version = "0.1.0"
readme = "README.md"
edition = "2021"
rust-version = "1.80"

[[bin]]
name = "porky"
path = "src/porky.rs"

[features]
default = ["usb-raw", "no_std"]
no_std = []
debug-probe = []
usb-tcp = ["usb"]
usb-raw = ["usb"]
usb = ["embassy-usb"]

[dependencies]
embassy-time = { version = "0.3.2", default-features = false, features = ["defmt", "defmt-timestamp-uptime"] }
embassy-executor = { version = "0.6.0", default-features = false, features = ["task-arena-size-65536", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-rp = { version = "0.2.0", default-features = false, features = ["rp2040", "defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-net = { version = "0.4.0", default-features = false, features = ["defmt", "tcp", "udp", "dns", "dhcpv4"] }
cyw43 = { version = "0.2.0", default-features = false, features = ["defmt"] }
cyw43-pio = { version = "0.2.0", default-features = false, features = ["defmt"] }
panic-probe = { version = "0.3", default-features = false, features = ["print-defmt"] }
portable-atomic = { version = "1.5", default-features = false, features = ["critical-section"] }
defmt = { version = "0.3", default-features = false }
defmt-rtt = { version = "0.4", default-features = false }
cortex-m-rt = { version = "0.7.0", default-features = false }
static_cell = { version = "2", default-features = false }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
embassy-sync = { version = "0.6.0", default-features = false }
embassy-futures = { version = "0.1.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
# To convert device_id into hex for use as a string
faster-hex = { version = "0.10.0", default-features = false }

serde = { version = "1.0.208", default-features = false, features = ["derive"] } # no_std
postcard = { version = "1.0.10", default-features = false, features = ["heapless"] }
heapless = { version = "0.8.0", default-features = false, features = ["serde"] }

ekv = { version = "1.0.0", default-features = false }
embedded-storage = { version = "0.3", default-features = false }

# Optional Dependencies
embassy-usb = { version = "0.3.0", default-features = false, optional = true }

[build-dependencies]
# for reading SSID config from a file in build.rs
serde_derive = "~1.0"
serde = "~1.0"
toml = { version = "0.8.8" }

[profile.release]
opt-level = "s"
lto = "fat"
panic = "abort"
strip = "debuginfo"

[patch.crates-io]
# make sure to get the latest git rev from GitHub, you can see the latest one here:
# https://github.com/embassy-rs/embassy/commits/main/
embassy-time = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-net = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy.git" }
cyw43 = { git = "https://github.com/embassy-rs/embassy.git" }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git" }

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
denylist = ["usb"]
always_include_features = ["no_std"]
# Features "usb-raw" and "usb-tcp" are incompatible, so skip permutations including them
skip_feature_sets = [
    ["usb-raw", "usb-tcp"],
]