all: build

clean:
	cargo clean

run:
	cargo run --release

build:
	cargo build --release

#TODO
#config: build
#	@cd .. && cargo run -p configr -- MOVISTAR_8A9E E68N8MA422GRQJQTPqjN target/thumbv6m-none-eabi/release/picomon