[package]
name = "pigdef"
description = "Core struct and const definitions for multiple crates in the pigg project"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
exclude.workspace = true
rust-version.workspace = true

[features]
default = ["iroh", "tcp", "usb", "discovery"]
tcp = []
discovery = []
no_std = []
usb = []
iroh = []

[dependencies]
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
# for config serialization to/from file
serde_json = { version = "1.0.138", default-features = false, features = ["std"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tempfile = "3"
