name: Build UF2 and attach to release

on:
  release:
    types: [ published ]

jobs:
  porky-release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: add thumbv6m-none-eabi target
        run: rustup target add thumbv6m-none-eabi

      - name: Build UF2 file for porky
        run: cd porky && RUSTFLAGS= make uf2